### ISSUE TITLE
[bug] Huggingface Pytorch 1.9.1 inference container not logging to CloudWatch

### ISSUE THREAD

**Issue by russkociuba** [aws/deep-learning-containers#1733] opened 2022-03-04 00:02 UTC
Checklist
- [x] I've prepended issue tag with type of change: [bug]
- [ ] (If applicable) I've attached the script to reproduce the bug
- [x] (If applicable) I've documented below the DLC image/dockerfile this relates to
- [ ] (If applicable) I've documented below the tests I've run on the DLC image
- [x] I'm using an existing DLC image listed here: https://docs.aws.amazon.com/deep-learning-containers/latest/devguide/deep-learning-containers-images.html
- [ ] I've built my own container based off DLC (and I've attached the code used to build my own image)

*Concise Description:*
The Huggingface Pytorch 1.9.1 inference container logs do not appear in CloudWatch.  As you can imagine this make things incredibly difficult to debug.  The roto cause seems to be due to a few incompatible versions of libraries being used.

*DLC image/dockerfile:*  763104351884.dkr.ecr.us-east-1.amazonaws.com/huggingface-pytorch-inference:1.9.1-transformers4.12.3-gpu-py38-cu111-ubuntu20.04

*Current behavior:*
No logs appear in CloudWatch from the container

*Expected behavior:*
Logs from the container appear in CloudWatch

*Additional context:*
From what I could track down this seems to be an issue related to log4j fixes in the multi-model-server code.  The container uses the [sagemaker-huggingface-inference-toolkit](https://github.com/aws/sagemaker-huggingface-inference-toolkit) which essentially extends from [sagemaker-inference-toolkit](https://github.com/aws/sagemaker-inference-toolkit).  The issue seems to step from using the [default log config](https://github.com/aws/sagemaker-huggingface-inference-toolkit/blob/7cb5009fef6566199ef47ed9ca2a3de4f81c0844/src/sagemaker_huggingface_inference_toolkit/mms_model_server.py#L23) which, for the version used in the container, is a log4j properties file.  However the version of multi-model-server packaged in the container was updated for log4j2 and the latest sagemaker-inference code uses a log4j2.xml file.

This can be demonstrated pretty easily.

1. Run the container and get a shell: `docker run -it --rm 763104351884.dkr.ecr.us-east-1.amazonaws.com/huggingface-pytorch-inference:1.9.1-transformers4.12.3-gpu-py38-cu111-ubuntu20.04 bash`
2. `cd /opt/conda/lib/python3.8/site-packages/mms/frontend/`
3. Run the MMS.  This is essentially what the toolkit code calls:  `java -cp model-server.jar -Dlog4j.configurationFile=/opt/conda/lib/python3.8/site-packages/sagemaker_inference/etc/log4j.properties com.amazonaws.ml.mms.ModelServer`

You can see the output is just `Model server started.`.  Now switch to log4j2:

1. Grab the new config file:  `curl -o /opt/conda/lib/python3.8/site-packages/sagemaker_inference/etc/log4j2.xml https://raw.githubusercontent.com/aws/sagemaker-inference-toolkit/master/src/sagemaker_inference/etc/log4j2.xml`
2. Run the MMS but with the new config: `java -cp model-server.jar -Dlog4j.configurationFile=/opt/conda/lib/python3.8/site-packages/sagemaker_inference/etc/log4j2.xml com.amazonaws.ml.mms.ModelServer`

You should get much more output:
```
MMS Home: /opt/conda/lib/python3.8/site-packages
Current directory: /opt/conda/lib/python3.8/site-packages/mms/frontend
Temp directory: /tmp
Number of GPUs: 0
Number of CPUs: 8
Max heap size: 2793 M
Python executable: python
Config file: N/A
Inference address: http://127.0.0.1:8080
Management address: http://127.0.0.1:8081
<snip>
```

**Comment by abist-kobayashi** [comment] 2022-03-06 16:08
I got a similar issue when I deploy the custom code with PyTorch deep learning container!
Here's the using container and results.

No logs appear(as @russkociuba described!): 763104351884.dkr.ecr.us-east-1.amazonaws.com/pytorch-inference:1.10.0-cpu-py38-ubuntu20.04-e3 
logs appear: 763104351884.dkr.ecr.us-east-1.amazonaws.com/pytorch-inference:1.8.1-cpu-py36-ubuntu18.04

**Comment by philschmid** [comment] 2022-04-20 16:37
should be fixed in this PR #1823, just need to re-release it.

**Comment by lasmith** [comment] 2022-04-20 19:15
Have also seen this behaviour and agree with @russkociuba the image is essentially broken if you cannot see any of the logs. Is there a simple workaround that can be applied to resolve this in the meantime?

To confirm replicated this on this image: 763104351884.dkr.ecr.eu-west-2.amazonaws.com/huggingface-pytorch-inference:1.9.1-transformers4.12.3-cpu-py38-ubuntu20.04

**Comment by philschmid** [comment] 2022-04-21 06:42
Yes you can simply use the PyTorch 1.10 & Transformers 4.17.0 version. You can find a list of all available versions here: https://huggingface.co/docs/sagemaker/reference#inference-dlc-overview

**Comment by lasmith** [comment] 2022-04-21 09:46
Nice thanks @philschmid I was taking the list of available DLC's from [here](https://github.com/aws/deep-learning-containers/blob/master/available_images.md) which is out of date. That solved the problem :)

**Comment by tejaschumbalkar** [comment] 2023-03-22 05:36
Closing the issue. Feel free to reopen if the issue is still seen

**Closed by tejaschumbalkar** 2023-03-22 05:36 UTC
