### ISSUE TITLE
[feature-request] Support for EAI for framework 1.6.0/1.7.0

### ISSUE THREAD

**Issue by anotinelg** [aws/deep-learning-containers#288] opened 2020-06-18 22:12 UTC
Hi, 

do you have an ETA for supporting Elastic inference with the 1.6.0 framework?
And also, are you going to add to this repository the docker files for the old 1.4.1 framework?
Thank you

Checklist
- [ ] I've prepended issue tag with type of change: [feature]
- [ ] (If applicable) I've documented below the DLC image/dockerfile this relates to
- [ ] (If applicable) I've documented the tests I've run on the DLC image
- [ ] I'm using an existing DLC image listed here: https://docs.aws.amazon.com/deep-learning-containers/latest/devguide/deep-learning-containers-images.html
- [ ] I've built my own container based off DLC (and I've attached the code used to build my own image)

*Concise Description:*

*DLC image/dockerfile:*

*Is your feature request related to a problem? Please describe.*

*Describe the solution you'd like*

*Describe alternatives you've considered*

*Additional context*

**Comment by anankira** [comment] 2020-06-19 19:36
@anotinelg Thanks for your interest ! We are working on migrating EIA Dockerfiles to this repo and on upgrades. But I don't have a timeline that I can share with you yet.

**Comment by bachsh** [comment] 2020-08-01 20:26
+1 on this. Even updated images for 1.5.1 would do (for me at least). @anankira if there's a way you can guide us through we will happily submit a PR.

**Comment by MarkG** [comment] 2020-08-02 19:10
+1
Have same problem. @anankira, same as @bachsh said, it will be very helpful somehow to get to the updated image.

**Comment by anankira** [comment] 2020-08-02 19:57
@MarkG @bachsh Ack, we will provide an update soon on the Elastic inference DLC updates for Pytorch.

@anotinelg  To clarify, are you looking for Elastic inference support for **MXNet**-1.6 ?

**Comment by bachsh** [comment] 2020-09-03 21:27
@anankira , any news on this? I'd like to point out that using EIA is the only thing that makes us interested in SageMaker for inference (due to the cost reduction).
And again, if there's a way you can guide us or point us to the relevant resources on how to create the images we will happily contribute to the repo.

**Comment by anankira** [comment] 2020-09-03 21:54
@bachsh thanks for that feedback. I am communicating with the AWS Elastic Inference team and will respond.

**Comment by samskalicky** [comment] 2020-09-11 17:19
@anotinelg, for MXNet we're planning to skip 1.6 and go straight to 1.7 in the next month or so. 

@bachsh and @MarkG, for PyTorch we're planning to skip 1.4 and go straight to 1.5 and 1.6 in the next month or so.

As we get closer to release we'll update this issue again.

**Comment by ralish** [comment] 2020-09-15 23:53
Just a note that it would be great if AWS documentation could be more explicit as to the PyTorch version support across various platforms. We've just discovered that PyTorch 1.3.1 is the latest supported release with EIA, which doesn't seem to be explicitly stated anywhere? It's sort of implied by it being the latest available wheel in the S3 bucket, but it's quite confusing when there's numerous AWS blog posts and associated articles announcing support for newer PyTorch releases.

**Comment by anankira** [comment] 2020-09-16 00:05
@ralish The Deep Learning Containers docs maintain the [available versions](https://docs.aws.amazon.com/deep-learning-containers/latest/devguide/deep-learning-containers-images.html) (that page actually leads back to a [page](https://github.com/aws/deep-learning-containers/blob/master/available_images.md) on this repo BTW)

**Comment by ralish** [comment] 2020-09-16 00:49
@anankira Thanks for that. I think part of the issue is we're not running an AWS Deep Leaning container but installing the PyTorch EIA wheel on our underlying distribution. As far as I'm aware, PyTorch 1.3.1 is the latest supported PyTorch for EIA via any mechanism, be that an AWS Deep Learning AMI, an AWS Deep Learning Docker container, or directly installing the wheel on a Linux distribution. If so, the supported version(s) should be more prominently displayed?

As we're installing the wheel we didn't look under the Docker container image documentation. The supported ML frameworks and associated versions feels to me quite fundamental and should be displayed on a page of its own in the AWS documentation, or a more generic page not specific to containers or AMIs.

**Comment by anankira** [comment] 2020-09-16 18:22
@ralish That's good feedback. We will work on updating the [Elastic Inference docs](https://docs.aws.amazon.com/elastic-inference/latest/developerguide/ei-pytorch-using.html).

**Comment by anotinelg** [comment] 2020-11-04 11:04
> @anotinelg, for MXNet we're planning to skip 1.6 and go straight to 1.7 in the next month or so.
> 
> @bachsh and @MarkG, for PyTorch we're planning to skip 1.4 and go straight to 1.5 and 1.6 in the next month or so.
> 
> As we get closer to release we'll update this issue again.

Hi @samskalicky, @anankira do you have some news on the release of eia for mxnet 1-7?
Thanks

**Comment by samskalicky** [comment] 2020-11-04 17:37
Hi @anotinelg the upgrade to MX 1.7 is on-going, we're looking at sometime in January for it to be complete.

**Comment by anotinelg** [comment] 2020-11-04 20:36
> Hi @anotinelg the upgrade to MX 1.7 is on-going, we're looking at sometime in January for it to be complete.

Thanks for the information!
Meanwhile, what do you recommend? what is the version of mxnet (superior to 1.4.1) which has images for both training-gpu, and inference eia? the 1.5.2? thanks

**Comment by samskalicky** [comment] 2020-11-05 01:54
> > Hi @anotinelg the upgrade to MX 1.7 is on-going, we're looking at sometime in January for it to be complete.
> 
> Thanks for the information!
> Meanwhile, what do you recommend? what is the version of mxnet (superior to 1.4.1) which has images for both training-gpu, and inference eia? the 1.5.2? thanks

unfortunately it looks like there was a lapse and theres no 1.5.0 or 1.5.1 training container unless @saimidu knows of anything else. 

So to use 1.5.1 inference container for EI you would need to train with 1.4.1 (older versions of trained models can run in newer versions for inference, but not vice-versa). Once we finish getting the 1.7 EI release out then there will be a nice pair of 1.7 training/inference containers

**Comment by fra-luc** [comment] 2020-11-05 08:50
Hi all, do you an have ETA on EIA support for PyTorch 1.6.0? Thanks!

**Comment by tracycxw** [comment] 2020-11-05 18:50
Hi @fra-luc ,
The upgrade to PyTorch 1.6.0 is on-going, we're looking at sometime in February to fully support it.

**Comment by fra-luc** [comment] 2020-11-05 21:01
Thank you @tracycxw

**Comment by anotinelg** [comment] 2021-02-09 12:47
> Hi @anotinelg the upgrade to MX 1.7 is on-going, we're looking at sometime in January for it to be complete.

Hi @samskalicky, last ETA for 1.7 eia was january. is there an update on that?
Thank you very much
Antoine

**Comment by samskalicky** [comment] 2021-02-09 21:48
Hi @anotinelg,

We're almost there! We've released the binary to the S3 bucket mentioned in the [docs](https://docs.aws.amazon.com/elastic-inference/latest/developerguide/ei-python.html#mxnet-package). The HTTP URL is:
https://amazonei-apachemxnet.s3.amazonaws.com/eimx-1.0-py2.py3-none-manylinux1_x86_64.whl

However, we have not yet finished updating the docs (they are still current for the previous 1.5.1 release) and are not valid for the latest 1.7 release. So YMMV until we finish updating the docs and examples. We expect this to happen soon in the next few weeks. 

We'll update here once the docs/examples are updated/live.

**Comment by anotinelg** [comment] 2021-02-10 08:28
> Hi @anotinelg,
> 
> We're almost there! We've released the binary to the S3 bucket mentioned in the [docs](https://docs.aws.amazon.com/elastic-inference/latest/developerguide/ei-python.html#mxnet-package). The HTTP URL is:
> https://amazonei-apachemxnet.s3.amazonaws.com/eimx-1.0-py2.py3-none-manylinux1_x86_64.whl
> 
> However, we have not yet finished updating the docs (they are still current for the previous 1.5.1 release) and are not valid for the latest 1.7 release. So YMMV until we finish updating the docs and examples. We expect this to happen soon in the next few weeks.
> 
> We'll update here once the docs/examples are updated/live.

Great news @samskalicky ! thanks for the update
In the meantime, i guess i can use the binary, and create a DockerImage more or less as you create the 1.5.1 but replacing the correct whl binary url, right?

**Comment by samskalicky** [comment] 2021-02-10 18:12
> Great news @samskalicky ! thanks for the update
> In the meantime, i guess i can use the binary, and create a DockerImage more or less as you create the 1.5.1 but replacing the correct whl binary url, right?

Unfortunately its not that simple. Without pasting all the new docs here, heres a quick summary:

In MX 1.6.0 they added a new "Accelerator API" aka "Extensions" support to dynamically load custom functionality into MXNet at runtime. For EIA we leveraged this to create an EIA library for our custom interface with the Elastic Inference service. This means for 1.7.0 you need a regular (non-EIA) MXNet installation and the AWS EIA library (the url linked in the previous post). This new wheel is much smaller (since it doesnt contain the actual MXNet installation, just our custom EIA components). 

To use this new wheel you would so something like:
```
import mxnet as mx
import eimx # new package loads EIA components

# Load saved model
sym, arg_params, aux_params = mx.model.load_checkpoint(model_path, EPOCH_NUM)

# new step for 1.7.0 to prepare your model for running on the EI accelerator
ei_sym = sym.optimize_for('EIA')

# regular MXnet flow
mod = mx.mod.Module(symbol=ei_sym, context=mx.cpu())
mod.bind(for_training=False, data_shapes=data_shape)
mod.set_params(arg_params, aux_params)

mod.forward(data_batch)
```

**Comment by nisalupendra** [comment] 2021-02-12 14:43
Do you have any update on ei-pytorch 1.7 or at least 1.6?

**Comment by tracycxw** [comment] 2021-02-13 03:39
> Hello, 
> 
> Do you have any update on ei-pytorch 1.7 or at least 1.6?

Hi, 

Could you try ei-pytorch 1.5.1 that we've released and see if it can meet your requirements?

**Comment by nisalupendra** [comment] 2021-02-15 10:06
> > Hello,
> > Do you have any update on ei-pytorch 1.7 or at least 1.6?
> 
> Hi,
> 
> Could you try ei-pytorch 1.5.1 that we've released and see if it can meet your requirements?

Hello,
Thank you for your response, 1.5.1 works well for us, but the problem is that we just need the pytorch 1.5.1 wheels, not mxnet neither the AMI (Since it's too large). Unfortunately I cannot find a link. It is not present in this [S3 bucket](https://s3.console.aws.amazon.com/s3/buckets/amazonei-pytorch/?region=us-east-1&tab=objects) mentioned in the docs either.
Could you please point me to a link to download the wheel?

**Comment by tracycxw** [comment] 2021-02-15 17:09
> > > Hello,
> > > Do you have any update on ei-pytorch 1.7 or at least 1.6?
> > 
> > 
> > Hi,
> > Could you try ei-pytorch 1.5.1 that we've released and see if it can meet your requirements?
> 
> Hello,
> Thank you for your response, 1.5.1 works well for us, but the problem is that we just need the pytorch 1.5.1 wheels, not mxnet neither the AMI (Since it's too large). Unfortunately I cannot find a link. It is not present in this [S3 bucket](https://s3.console.aws.amazon.com/s3/buckets/amazonei-pytorch/?region=us-east-1&tab=objects) mentioned in the docs either.
> Could you please point me to a link to download the wheel?

Hi,
This link should work https://amazonei-pytorcheia.s3.amazonaws.com/releases/v1.0.0/torcheia-1.0.0-cp36-cp36m-manylinux1_x86_64.whl
Clicking on this will directly download the latest wheel for torcheia v1.0.0 (which is the client for PyTorch 1.5.1). 
Thank you for the feedback, we will update our docs ASAP :)

**Comment by Bellk17** [comment] 2021-03-02 04:23
Hi! Also curious if there is any movement on PyTorch 1.6+ support, as architecture is reliant on features not available in 1.5.1.

**Comment by samskalicky** [comment] 2021-03-03 00:00
Hi @Bellk17 we just completed the release with PT 1.5.1. We're still evaluating post-1.5.1 versions moving forward and will post here when we have an update.

**Comment by anotinelg** [comment] 2021-04-15 10:58
Hi @samskalicky, i guess you finally release mxnet 1.7 eia, right?
I finally can see some dockerfile.eia in the repo: https://github.com/aws/deep-learning-containers/blob/master/mxnet/inference/docker/1.7.0/py3/Dockerfile.eia
and mxnet-1.7-eia is listed in https://github.com/aws/deep-learning-containers/blob/master/available_images.md

What i can not find is the documentation to use it? did you manage to update the doc?

Thank you very much

**Comment by samskalicky** [comment] 2021-04-15 15:46
> Hi @samskalicky, i guess you finally release mxnet 1.7 eia, right?
> I finally can see some dockerfile.eia in the repo: https://github.com/aws/deep-learning-containers/blob/master/mxnet/inference/docker/1.7.0/py3/Dockerfile.eia
> and mxnet-1.7-eia is listed in https://github.com/aws/deep-learning-containers/blob/master/available_images.md
> 
> What i can not find is the documentation to use it? did you manage to update the doc?
> 
> Thank you very much

Hi @anotinelg , sorry for the delay in notification. Yes MXNet 1.7 support for EIA has been completed. The standard docs have been updated, heres the link: https://docs.aws.amazon.com/elastic-inference/latest/developerguide/ei-python.html Let us know how it works for you.

**Comment by anotinelg** [comment] 2021-04-15 16:14
> > Hi @samskalicky, i guess you finally release mxnet 1.7 eia, right?
> > I finally can see some dockerfile.eia in the repo: https://github.com/aws/deep-learning-containers/blob/master/mxnet/inference/docker/1.7.0/py3/Dockerfile.eia
> > and mxnet-1.7-eia is listed in https://github.com/aws/deep-learning-containers/blob/master/available_images.md
> > What i can not find is the documentation to use it? did you manage to update the doc?
> > Thank you very much
> 
> Hi @anotinelg , sorry for the delay in notification. Yes MXNet 1.7 support for EIA has been completed. The standard docs have been updated, heres the link: https://docs.aws.amazon.com/elastic-inference/latest/developerguide/ei-python.html Let us know how it works for you.

Great
we will try ASP
Thank you @samskalicky 

I guess we can close that thread

**Comment by anotinelg** [comment] 2021-06-10 11:37
Hi @samskalicky, i was trying to implement the eia. with my 1.7.0 inference image. i  guess i will have to pass to mxnet 1.8.0. 
It seems that eia does not work for mxnet 1.7.0 and symbolic API, right ([Code](https://mxnet.apache.org/versions/1.7.0/api/python/docs/_modules/mxnet/gluon/block.html#Block))? however, looking at the code in 1.8.0, it seems that it can work [code](https://mxnet.apache.org/versions/1.8.0/api/python/docs/_modules/mxnet/gluon/block.html#Block).
Can you confirm this behaviour?
Thanks

**Comment by samskalicky** [comment] 2021-06-10 16:34
Hi @anotinelg, i dont quite understand your problem. Can you provide a code snippet thats not working for you?

The docs have examples for symbol API (in addition to Module & Gluon): https://docs.aws.amazon.com/elastic-inference/latest/developerguide/ei-python.html#install-mxnet

**Comment by anotinelg** [comment] 2021-06-11 09:10
> Hi @anotinelg, i dont quite understand your problem. Can you provide a code snippet thats not working for you?
> 
> The docs have examples for symbol API (in addition to Module & Gluon): https://docs.aws.amazon.com/elastic-inference/latest/developerguide/ei-python.html#install-mxnet

Sure! my code looks like the following:
```
# Getting the symbol files
from mxnet import gluon
import mxnet as mx
print(mx.__version__)
net1 = gluon.model_zoo.vision.resnet18_v1(prefix='resnet', pretrained=True)
net1.hybridize()
x = mx.nd.random.normal(shape=(1, 3, 32, 32))
out1 = net1(x)
net1.export('net1', epoch=1)

# Creating Symbol graph
net2 = gluon.SymbolBlock.imports('net1-symbol.json', ['data'], 'net1-0001.params')
out2 = net2(x)

#optimizing for EIA
net2.optimize_for("EIA")
```
the last line fails with:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-8-1dffbeb1fce3> in <module>
----> 1 net2.optimize_for("EIA")

~/anaconda3/envs/carclass/lib/python3.6/site-packages/mxnet/gluon/block.py in optimize_for(self, x, backend, backend_opts, *args, **kwargs)
   1078                              ' Please check the type of the args.\n')
   1079         if not has_symbol and not has_ndarray:
-> 1080             raise ValueError('In HybridBlock, there must be one NDArray as input.'
   1081                              ' Please check the type of the args.\n')
   1082         if len(ctx_set) > 1:

ValueError: In HybridBlock, there must be one NDArray as input. Please check the type of the args.
```

Looking at the code for mxnet [1.7.0](https://github.com/apache/incubator-mxnet/blob/1.7.0/python/mxnet/gluon/block.py#L1076)  and [1.8.0](https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/gluon/block.py#L1376) , we can see that 1.7.0 does not handle optimizing for eia with symbolblock. However for 1.8.0, it does

**Comment by samskalicky** [comment] 2021-06-11 15:36
Hi @anotinelg,

Thanks for the code. Please check out the example Gluon script for EIA here: https://docs.aws.amazon.com/elastic-inference/latest/developerguide/ei-python.html#ei-mxnet-gluon-api

The recommended usage is:
```
resnet50 = vision.resnet50_v1(pretrained=True, ctx=ctx)
resnet50.hybridize(backend="EIA", static_alloc=True, static_shape=True) # hybridize with EIA as backend
prob = resnet50(img).softmax() # predict and normalize output
```
where you use the `hybridize` API. The `sym.optimize_for('EIA')` is only for Symbol objects, not Gluon Blocks. For Gluon, you should use the recommended `hybridize` flow.

**Comment by arjkesh** [comment] 2021-07-13 20:09
Hey @anotinelg - does this recommendation work for your use case with the MX 1.7 EI containers? Feel free to reopen if there is any other information you need regarding this issue - we are closing this out for now. Thanks again for your interest in DLC!

**Closed by arjkesh** 2021-07-13 20:09 UTC
Labels: enhancement request
