### ISSUE TITLE
[bug] OpenCV is not installed properly by apt-get

### ISSUE THREAD

**Issue by SergTogul** [aws/deep-learning-containers#1261] opened 2021-08-09 21:53 UTC
Checklist
- [ ] I've prepended issue tag with type of change: [bug]
- [ ] (If applicable) I've attached the script to reproduce the bug
- [ ] (If applicable) I've documented below the DLC image/dockerfile this relates to
- [ ] (If applicable) I've documented below the tests I've run on the DLC image
- [ ] I'm using an existing DLC image listed here: https://docs.aws.amazon.com/deep-learning-containers/latest/devguide/deep-learning-containers-images.html
- [ ] I've built my own container based off DLC (and I've attached the code used to build my own image)

*Concise Description:*
Getting error from openCV
libdc1394 error: Failed to initialize libdc1394

*DLC image/dockerfile:*

*Current behavior:*

*Expected behavior:*
OpenCV installed correct way through apt-get

*Additional context:*
In a number of docker files we're using the following workaround:
https://stackoverflow.com/questions/29274638/opencv-libdc1394-error-failed-to-initialize-libdc1394

**Comment by tejaschumbalkar** [comment] 2024-02-27 06:00
Closing given the issue is more than 3 years old

**Closed by tejaschumbalkar** 2024-02-27 06:00 UTC
