### ISSUE TITLE
[bug]nvgpu missing in latest docker file for pytorch 2.0 training image

### ISSUE THREAD

**Issue by mksujith** [aws/deep-learning-containers#3054] opened 2023-05-31 12:11 UTC
Checklist
- [x] I've prepended issue tag with type of change: [bug]
- [ ] (If applicable) I've attached the script to reproduce the bug
- [ ] (If applicable) I've documented below the DLC image/dockerfile this relates to
- [ ] (If applicable) I've documented below the tests I've run on the DLC image
- [ ] I'm using an existing DLC image listed here: https://docs.aws.amazon.com/deep-learning-containers/latest/devguide/deep-learning-containers-images.html
- [ ] I've built my own container based off DLC (and I've attached the code used to build my own image)

*Concise Description:*
Prometheus mode logging failing due to missing nvgpu package.

*DLC image/dockerfile:*
The default Pytorch 2.0 training image [Dockerfile.gpu](https://github.com/aws/deep-learning-containers/blob/master/pytorch/inference/docker/2.0/py3/cu118/)

*Current behavior:*

Showing error to log org.pytorch.serve.metrics.MetricCollector and no Prometheus mode logging are available. Had to manually add steps to Docker file to enable nvgpu package

*Expected behavior:*

To have the Prometheus mode logging working with Docker Image (as in previous versions)

*Additional context:*

```
2023-05-30T08:50:48,339 [ERROR] Thread-1059 org.pytorch.serve.metrics.MetricCollector - Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/ts/metrics/metric_collector.py", line 27, in <module>
    system_metrics.collect_all(sys.modules['ts.metrics.system_metrics'], arguments.gpu)
  File "/opt/conda/lib/python3.10/site-packages/ts/metrics/system_metrics.py", line 119, in collect_all
    value(num_of_gpu)
  File "/opt/conda/lib/python3.10/site-packages/ts/metrics/system_metrics.py", line 64, in gpu_utilization
    import nvgpu
ModuleNotFoundError: No module named 'nvgpu'
```

**Comment by ohadkatz** [comment] 2023-06-29 14:21
Hi @mksujith

Are you intending to use NVGPU in a training image or inference image? You have linked to an inference GPU PyTorch 2.0 image, but have listed it as a training image.
 
Currently, nvgpu is only installed on our [inference images](https://github.com/aws/deep-learning-containers/blob/a2d5a5a5336ba87ec4c7ebc22f6b182a86a80324/pytorch/inference/docker/2.0/py3/cu118/Dockerfile.gpu#L187) as a result of it being a direct dependency of torchserve. As torchserve is only in scope for inference, we do not install nvgpu in training images.
 
On  763104351884.dkr.ecr.us-east-1.amazonaws.com/pytorch-inference:2.0.1-gpu-py310-cu118-ubuntu20.04-ec2 (inference image) I validated that nvgpu is present: 
 ```
 root@510bc13a2c21:/# pip freeze | grep 'nvgpu'
 nvgpu==0.10.0
 ```

If there is a use case for using nvgpu in training images, we can certainly intake this request and see if we can add nvgpu to our PyTorch training image for future pytorch releases.

**Comment by xncqr** [comment] 2023-07-28 03:08
Greetings,
```
DLC image/dockerfile:
The default Pytorch 2.0 training image [Dockerfile.gpu](https://github.com/aws/deep-learning-containers/blob/master/pytorch/inference/docker/2.0/py3/cu118/)
```
This link references the Dockerfile of our PT 2.0 Inference image, which shows nvgpu would be installed into the image.

The log snippet shows `org.pytorch.serve.metrics.MetricCollector` which is TorchServe, being Inference only and why you would even see an error regarding nvgpu missing.

@mksujith some questions:
* Are you attempting to serve a model or train it? 
* Have you tried the latest 2.0 images? 
* What is the URI of the image you are using?
* Are you modifying the images?

Hoping to get clarity for better support.

-Mike

**Comment by xncqr** [comment] 2023-08-09 15:07
@mksujith bump.. any updates or is all good now?

**Comment by arjkesh** [comment] 2023-08-11 22:54
@mksujith Thanks for your request and for using DLC! Given that the dockerfile linked in the issue is an inference DLC and does have nvgpu installed in the latest version, we are closing this issue out.

If you are still facing the issue, please feel free to reopen - the questions that @xncqr posed here - https://github.com/aws/deep-learning-containers/issues/3054#issuecomment-1654910868 - will be helpful if this issue persists.

**Closed by arjkesh** 2023-08-11 22:54 UTC
